### ISSUE TITLE
Clipboard items are missing

### ISSUE THREAD

**Issue by mhanberg** [mr-pennyworth/alfred-cleanshot#5]
I think that a recent CleanShot update may have broken some of the options that I'm used to seeing.

For example, I'm not longer seeing any of the options involving the clipboard, like Capture Area to Clipboard or Annotate Image from Clipboard.

Love this workflow, thanks a lot!

**Comment by mhanberg** [comment]
Perhaps "Capture Area to clipboard" was never an action, but Annotate from clipboard does indeed seem to be missing

**Comment by mr-pennyworth** [comment]
Glad to know that you've found this workflow useful, @mhanberg!

Sorry it's been quite long that I've forgotten how this works 🤣 
I took a quick look by searching for `clipboard`, turns out there are only two clipboard-based actions: https://github.com/mr-pennyworth/alfred-cleanshot/blob/03360ff9cc8413b79a60e77733e0abaf4970e0ab/items.sh#L127-L148
 - Annotate Image from Clipboard
 - Pin to the Screen from Clipboard

Both of these become available only when the clipboard contains image data.
Can you try this:
 1. Make sure your clipboard has image data
 2. Try the workflow
 3. See if the option shows up

If not, we might need to debug deeper, although I've got a feeling that it's just that they're not showing up because clipboard has some other data (and not image data).

First step to check would be to see if `pngpaste` works.

**Comment by mhanberg** [comment]
I'll double check tomorrow, thanks!

**Comment by mhanberg** [comment]
It appears that I had to `brew install pngpaste`.

I'm curious why it was working before, but nonetheless, i'm back in action.

Thanks!
